// Code generated by "core generate"; DO NOT EDIT.

package abm

import (
	"cogentcore.org/core/types"
)

var _ = types.AddType(&types.Type{Name: "github.com/kleroterio/abm/abm.ConfigBase", IDName: "config-base", Doc: "ConfigBase is the base type for configuration parameter sets.", Directives: []types.Directive{{Tool: "types", Directive: "add"}}, Fields: []types.Field{{Name: "Beliefs", Doc: "Beliefs is the number of belief axes in the simulation."}}})
