// Code generated by "core generate"; DO NOT EDIT.

package abm

import (
	"cogentcore.org/core/types"
)

var _ = types.AddType(&types.Type{Name: "github.com/kleroterio/abm/abm.ConfigBase", IDName: "config-base", Doc: "ConfigBase is the base type for configuration parameter sets.", Directives: []types.Directive{{Tool: "types", Directive: "add"}}, Fields: []types.Field{{Name: "Beliefs", Doc: "Beliefs is the number of political belief axes in the simulation."}, {Name: "ChangeVelocity", Doc: "ChangeVelocity is the chance that an agent will change its spatial velocity."}, {Name: "VelocityMultiplier", Doc: "VelocityMultiplier is a multiplier on the random spatial velocity at which\nagents move."}, {Name: "InteractionRadius", Doc: "InteractionRadius is the multiplier on the maximum squared distance between\nagents for an interaction to occur, with the base value being 1/n\n(n = total number of agents)."}, {Name: "InteractionEffect", Doc: "InteractionEffect is how much an interaction impacts beliefs as a\nproportion of the initial difference in beliefs."}, {Name: "ValueEffect", Doc: "ValueEffect is how much an agent's immutable values impact their beliefs\nas a proportion of the difference between beliefs and values.\nValues have a kind of restorative force, pulling beliefs back to the original\nvalues over time."}}})
